config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wordnasium, only: [:index]
  root 'wordnasium#index'
  resources :words do
  	collection do 
	  	get :filter
	  end
  end
  resources :meanings, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meaning.rb
class Meaning < ApplicationRecord
  belongs_to :word
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :words
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ApplicationRecord
	has_many :meanings,  dependent: :destroy
	belongs_to :user
	validates :aword, uniqueness: { case_sensitive: true, message: "Word exists in Wordnasium" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/meanings_controller.rb
class MeaningsController < ApplicationController
	def create
		
	end
end

app/controllers/wordnasium_controller.rb
class WordnasiumController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  skip_before_action :verify_authenticity_token

	def create
		@word = current_user.words.new(aword: params[:vocab][:aword])
		@word.meanings.build(describe: params[:vocab][:meaning])
		@word.save
	  respond_to do |format|
	    format.js {}
	  end
	end

	def index
		@words = Word.includes(:meanings).all
	  respond_to do |format|
	    format.js {}
	  end
	end

	def destroy
    if !current_user.words.empty?
         @word = current_user.words.find(params[:id].split("_").last.to_i)
		     @word.meanings.destroy_all && @word.delete if @word
         respond_to do |format|
     	    format.js {}
     	  end
    else
      # redirect_to :back
      redirect_back fallback_location: root_path #:flash => { :error => "You Can delete only Your Data" }
      flash[:notice] = "You Can delete or edit only your word"
    end

	end

	def show
		@word = Word.find(params[:id].split("_").last)
		#TODO Multiple field for meaning not implemented yet
		render json: {word: @word.aword, meaning: @word.meanings.first.describe}
	end

	def edit
		binding.pry
	end

	def filter
		@words = Word.where("aword ~* ?", "^#{params[:alpha_search]}")
	  respond_to do |format|
	    format.js {}
	  end
	end

	private
		def word_params
	    params[:vocab].require(:vocab).permit(:word)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/meanings_helper.rb
module MeaningsHelper
end

app/helpers/wordnasium_helper.rb
module WordnasiumHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Remembro</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= favicon_link_tag 'lightbulb.png', type: 'image/png' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= image_tag("lightbulb.png", alt: "logo", size:"35x35", class: "product-logo") %>
      <a class="navbar-brand">Remembro</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <form class="navbar pull-right">
        <ul class="nav">
          <% if user_signed_in? %>
              <li>Welcome, <%= current_user.email %>!</li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </form>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

<script type="text/javascript">
  $( ".navbar-brand" ).click(function() {
    $('#list-word-filter').empty();
    $("#list-word-filter").append("<img alt='logo' id='loader'src='/assets/loader.gif'>")
    $.get( "/words", function() {});
  });
  $( ".product-logo" ).click(function() {
    $(this).css("background", "radial-gradient(yellow, #f8f9fa, #f8f9fa)")
  });
</script>

app/views/wordnasium/_listword.html.erb
<% words.each_with_index do |word, index| %>
  <div class="card" id="card_<%= dom_id(word) %>">
    <div class="card-body">
    	<button id="remove_word_<%= dom_id(word) %>" class="btn btn-danger fa fa-close delete-word">
	    </button>
	    <% if born %>
	      <h5 class="card-title" id="<%= dom_id(word) %>"><b><br/><%= word.aword + " " %></b><span class="badge badge-warning new-message">New</span></h5>
	    <% else %>
		    <h5 class="card-title" id="<%= dom_id(word) %>"><b>#<%= index + 1 %><br/><%= word.aword %></b></h5>
	    <% end %>
      <h6 class="card-subtitle mb-2 text-muted">created at <%= word.created_at.strftime("%B %d, %Y") %></h6>
      	<% word.meanings.each do |meaning| %>
      		<p class="card-text" id="<%= dom_id(meaning)%>"><i><%= meaning.describe %></i></p>
      	<% end %>
    </div>
  </div>
<% end %>

<div class="modal fade" id="destroyer" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <i>Are you sure you want to delete this word?</i>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-danger affirm-del">Yes</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="edit-word" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add new word</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="edit-form">
          <div class="form-group">
            <label for="Word">Word</label>
            <input name="word" type="text" class="form-control" id="word_field">
          </div>
          <div class="form-group">
            <label for="Meaning">Meaning</label>
            <input name="meaning" type="text" class="form-control" id="meaning_field">
          </div>
          <button type="submit" class="btn btn-primary pull-right" id="edit-button">Edit</button>
        </form>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  $("#edit-button").on('click', function(){
    debugger
  });
  // $(".card").on('click', function(){
  //   $("#edit-word").modal('show');
  //   var card_id = $(this).attr('id')
  //   $.ajax({
  //     type: 'get',
  //     url: '/words/' + card_id,
  //       success: function(data) {
  //       $('#edit-word #word_field').val(data.word);
  //       $('#edit-word #meaning_field').val(data.meaning);
  //     }
  //   });
  // });
	$(".affirm-del").on("click", function () { 
    $.ajax({
    type: 'delete',
    url: '/words/' + $(this).attr('id'),
      success: function(data) {
        $('#destroyer').modal('hide')
      }
    });
	});
	$(".delete-word").on("click", function () {
		$(".affirm-del").attr('id', $(this).attr('id'))
		$("#destroyer").modal('show')
	});
</script>

app/views/wordnasium/index.html.erb
<div class="row">
  <div class="col-md-2" id="sidebar-container">
  <div class="sidebar">
    <ul class="list-group">
      <% ("A".."Z").to_a.shuffle.each do |alpha| %>
        <li class="list-group-item" id="alplabet_<%= alpha %>" style="text-align-last: center; " onclick="bring_words(this)"><%= alpha %></li>
      <% end %>
    </ul>
    </div>
  </div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add new word</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for :vocab, remote: true, url: words_path do |f| %>
          <%= f.input :aword, as: :string %>
          <%= f.input :meaning, as: :string %>
          <%= f.submit "Save changes", class:"btn btn-sm btn-primary pull-right", id:"save_word" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

  <div class="col-md-10" id="wordcanvas">
    <div class="row" id="task_list">
      <span id="task_bar" onclick="test()">
        <button type="button" id="add_new" class="btn btn-success fa fa-plus" data-toggle="tooltip" data-placement="top" title="Add new word">
        </button>
      </span>
    </div>
    <div class="row" id="chosen_word">
      <p><i>&nbsp Chosen Alphabet &nbsp</i></p>
      <span class="badge badge-pill badge-success alphashow" style="height: 58%;">All</span>
    </div>
    <div id="list-word-filter">
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
  $(".vocab").on('submit', function(){
    $('#save_word').removeAttr("disabled");
    $('#addModal').modal('hide');
  })
  function bring_words(caller){
    $('#list-word-filter').empty();
    $("#list-word-filter").append("<img alt='logo' id='loader'src='/assets/loader.gif'>")
    $(caller).css("background", "linear-gradient(to right, #deefe8, #fff)");
    var alpha = $(caller).attr('id').split('_')[1];
    $.ajax({
    type: 'get',
    url: '/words/filter',
    data: {alpha_search: alpha},
      success: function(data) {
        eval(data); 
      }
    });
  }
  function test(){
    $('#save_word').removeAttr("disabled");
    $('#addModal').modal('show');
  }
  $(document).ready(function(){
    $('#save_word').removeClass("disabled");
    $('#add_new').tooltip();
    $('#list-word-filter').empty();
    $("#list-word-filter").append("<img alt='logo' id='loader'src='/assets/loader.gif'>")
    $.get( "/words", function() {});
  });
</script>

app/views/words/create.js.erb
$('#list-word-filter').prepend("<%= escape_javascript render(:partial => 'wordnasium/listword', :locals => { :words => [@word], :born => true }) %>");

app/views/words/destroy.js.erb
$("#card_<%= dom_id(@word)%>").fadeOut(300, function(){ 
	$(this).remove();
});

app/views/words/filter.js.erb
$('#list-word-filter').empty();
$("#loader").remove();
$('#list-word-filter').append("<%= escape_javascript render(:partial => 'wordnasium/listword', :locals => { :words => @words, :born => false }) %>");
$('.alphashow').html("<%= params[:alpha_search] %>")

app/views/words/index.js.erb
$("#loader").remove();
$('#list-word-filter').html("<%= escape_javascript render(:partial => 'wordnasium/listword', :locals => { :words => @words, :born => false }) %>");
$('.alphashow').html("All")